directcat_shuf (Spike Train Analysis Toolkit)
Spike Train Analysis Toolkit Documentation Spike Train Analysis Toolkit Function Reference directcat_shuf
Spike Train Analysis Toolkit
directcat_shuf
DIRECTCAT_SHUF Direct method analysis to determine category-specific information with shuffled inputs.
   [Y,SHUF] = DIRECTCAT_SHUF(X,OPTS,S) performs a direct method
   analysis on input data structure X. In addition to the typical
   analysis, this function also analyzes S versions of X with the
   categories randomly shuffled. Y is an output structure with the
   results of the typical analysis and SHUF is an Sx1 array of output
   structures with the results for each category permutation. For
   information on the output structure, see DIRECTCAT.
   For information on options and parameters see DIRECT.
   [Y,SHUF] = DIRECTCAT_SHUF(X,[],S) uses the default options and parameters.
   [Y,SHUF,OPTS_USED] = DIRECTCAT_SHUF(X,[],S) or [Y,SHUF,OPTS_USED] =
   DIRECTCAT_SHUF(X,OPTS,S) additionally return the options used.
   See also DIRECTCAT, DIRECTCAT_JACK.
Cross-reference information
This function calls:
directcat DIRECTCAT Direct method analysis to determine category-specific information.
directcountcond DIRECTCOUNTCOND Count spike train words in each class and disregarding class.
infocond INFOCOND Information and entropies from conditional and total
This function is called by: