directcountcond (Spike Train Analysis Toolkit)
Spike Train Analysis Toolkit Documentation Spike Train Analysis Toolkit Function Reference directcountcond
Spike Train Analysis Toolkit
directcountcond
DIRECTCOUNTCOND Count spike train words in each class and disregarding class.
   Y = DIRECTCOUNTCOND(X,OPTS) counts the words in cell array X and
   stores the results in a HISTCOND data structure Y. Y consists of
   two substructures. Y.TOTAL is a HIST1D structure that contains the
   results of counting all of the words in X. Y.CLASS is a HIST1DVEC
   array that contains the results of counting the words in X
   segregated by category.
   There are currently no user-specified options or parameters for
   this function. Therefore OPTS is ignored.
   Y = DIRECTCOUNTCOND(X) has exactly the same behavior as above.
   [Y,OPTS_USED] = DIRECTCOUNTCOND(X,OPTS) copies OPTS into OPTS_USED.
   See also DIRECTBIN, DIRECTCONDCAT, DIRECTCONDTIME,
   DIRECTCONDFORMAL, DIRECTCOUNTCLASS, DIRECTCOUNTTOTAL, INFOCOND.
Cross-reference information
This function calls:
This function is called by:
directcat DIRECTCAT Direct method analysis to determine category-specific information.
directcat_jack DIRECTCAT_JACK Direct method analysis to determine category-specific information with leave-one-out jackknife.
directcat_shuf DIRECTCAT_SHUF Direct method analysis to determine category-specific information with shuffled inputs.