directcat_jack (Spike Train Analysis Toolkit)
Spike Train Analysis Toolkit Documentation Spike Train Analysis Toolkit Function Reference directcat_jack
Spike Train Analysis Toolkit
directcat_jack
DIRECTCAT_JACK Direct method analysis to determine category-specific information with leave-one-out jackknife.
   [Y,JK] = DIRECTCAT_JACK(X,OPTS) performs a direct method
   analysis on input data structure X. In addition to the typical
   analysis, this function also does a leave-one-out jackknife. Y
   is an output structure with the results of the typical analysis
   and JK is an array of output structures with the results for each
   jackknife trial. There are as many elements in JK as there are
   spike trains in X. For information on the output structure, see
   DIRECTCAT.
   For information on options and parameters see DIRECT.
   [Y,JK] = DIRECTCAT_JACK(X) uses the default options and parameters.
   [Y,JK,OPTS_USED] = DIRECTCAT_JACK(X) or [Y,JK,OPTS_USED] =
   DIRECT_JACK(X,OPTS) additionally return the options used.
   See also DIRECTCAT, DIRECTCAT_SHUF.
Cross-reference information
This function calls:
directcat DIRECTCAT Direct method analysis to determine category-specific information.
directcountcond DIRECTCOUNTCOND Count spike train words in each class and disregarding class.
infocond INFOCOND Information and entropies from conditional and total
This function is called by: