info2d (Spike Train Analysis Toolkit)
Spike Train Analysis Toolkit Documentation Spike Train Analysis Toolkit Function Reference info2d
Spike Train Analysis Toolkit
info2d
INFO2D Information and entropies from a 2-D histogram.
   Y = INFO2D(X,OPTS) takes a HIST2D structure X and copies it to
   Y, adding estimates of entropies and mutual
   information. Y.INFORMATION is an ESTIMATE structure
   corresponding to the mutual information. ESTIMATE structures
   corresponding to entropies are added to Y.ROW, Y.COL, and
   Y.JOINT.
   The options and parameters for this function are:
      OPTS.ENTROPY_ESTIMATION_METHOD
      OPTS.VARIANCE_ESTIMATION_METHOD: A cell array of variance
      estimation methods.
   Please see the Spike Train Analysis Toolkit documentation for
   more information.
   Y = INFO2D(X) does not do any bias correction or variance
      estimation.
   [Y,OPTS_USED] = INFO2D(X,OPTS) copies OPTS into OPTS_USED.
   See also MATRIX2HIST2D, INFOCOND, ENTROPY1D.
Cross-reference information
This function calls:
This function is called by:
metric METRIC Metric space analysis
metric_jack METRIC_JACK Metric space analysis with leave-one-out jackknife.
metric_shuf METRIC_SHUF Metric space analysis with shuffled inputs.