infocond (Spike Train Analysis Toolkit)
Spike Train Analysis Toolkit Documentation Spike Train Analysis Toolkit Function Reference infocond
Spike Train Analysis Toolkit
infocond
INFOCOND Information and entropies from conditional and total
histograms.
   Y = INFOCOND(X,OPTS) takes a HISTCOND structure X and copies it to
   Y, adding estimates of entropies and mutual
   information. Y.INFORMATION is an ESTIMATE structure corresponding
   to the mutual information. ESTIMATE structures corresponding to
   entropies are added to Y.CLASS and Y.TOTAL.
   The options and parameters for this function are:
      OPTS.ENTROPY_ESTIMATION_METHOD
      OPTS.VARIANCE_ESTIMATION_METHOD: A cell array of variance
      estimation methods.
   Please see the Spike Train Analysis Toolkit documentation for
   more information.
   Y = INFOCOND(X) does not perform any bias correction or variance
      estimation.
   [Y,OPTS_USED] = INFOCOND(X,OPTS) copies OPTS into OPTS_USED.
   See also MATRIX2HIST2D, INFO2D, ENTROPY1D.
Cross-reference information
This function calls:
This function is called by:
directcat DIRECTCAT Direct method analysis to determine category-specific information.
directcat_jack DIRECTCAT_JACK Direct method analysis to determine category-specific information with leave-one-out jackknife.
directcat_shuf DIRECTCAT_SHUF Direct method analysis to determine category-specific information with shuffled inputs.
directformal DIRECTFORMAL Direct method analysis to determine formal information.