metric_shuf (Spike Train Analysis Toolkit)
Spike Train Analysis Toolkit Documentation Spike Train Analysis Toolkit Function Reference metric_shuf
Spike Train Analysis Toolkit
metric_shuf
METRIC_SHUF Metric space analysis with shuffled inputs.
   [Y,SHUF] = METRIC_SHUF(X,OPTS,S) performs a metric space method
   analysis on input data structure X. In addition to the typical
   analysis, this function also analyzes S versions of X with the
   categories randomly shuffled. Y is an output structure with the
   results of the typical analysis and SHUF is an Sx1 array of output
   structures with the results for each category permutation. For
   information on the output structure, see METRIC.
   For information on options and parameters see METRIC.
   [Y,SHUF] = METRIC_SHUF(X,[],S) uses the default options and parameters.
   [Y,SHUF,OPTS_USED] = METRIC_SHUF(X,[],S) or [Y,SHUF,OPTS_USED] =
   METRIC_SHUF(X,OPTS,S) additionally return the options used.
   See also METRIC, METRIC_JACK.
Cross-reference information
This function calls:
info2d INFO2D Information and entropies from a 2-D histogram.
matrix2hist2d MATRIX2HIST2D Converts a 2-D matrix of counts to a 2-D histogram.
metric METRIC Metric space analysis
metricclust METRICCLUST Cluster spike trains based on distance matrix.
This function is called by: