metric_jack (Spike Train Analysis Toolkit)
Spike Train Analysis Toolkit Documentation Spike Train Analysis Toolkit Function Reference metric_jack
Spike Train Analysis Toolkit
metric_jack
METRIC_JACK Metric space analysis with leave-one-out jackknife.
   [Y,JK] = METRIC_JACK(X,OPTS) performs a metric space method
   analysis on input data structure X. In addition to the typical
   analysis, this function also does a leave-one-out jackknife. Y
   is an output structure with the results of the typical analysis
   and JK is an array of output structures with the results for
   each jackknife trial. There are as many elements in JK as there
   are spike trains in X. For information on the output structure,
   see METRIC.
   For information on options and parameters see METRIC.
   [Y,JK] = METRIC_JACK(X) uses the default options and parameters.
   [Y,JK,OPTS_USED] = METRIC_JACK(X) or [Y,JK,OPTS_USED] =
   METRIC_JACK(X,OPTS) additionally return the options used.
   See also METRIC, METRIC_SHUF.
Cross-reference information
This function calls:
info2d INFO2D Information and entropies from a 2-D histogram.
matrix2hist2d MATRIX2HIST2D Converts a 2-D matrix of counts to a 2-D histogram.
metric METRIC Metric space analysis
metricclust METRICCLUST Cluster spike trains based on distance matrix.
This function is called by: