function fig = crossfigureg()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load crossfigureg

h0 = figure('Units','centimeters', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','D:\Matlab\user\crossfigureg.m', ...
	'KeyPressFcn','ctlpanel KeyPress', ...
	'MenuBar','none', ...
	'Name','XCorel Raw Data Analysis: V1.9', ...
	'NumberTitle','off', ...
	'PaperPosition',[18.00000000000001 180 576.0000000000002 432.0000000000001], ...
	'PaperType','A4', ...
	'PaperUnits','points', ...
	'PointerShapeCData',mat1, ...
	'Position',[8.433795104166668 0.5816410416666666 18.21593989583333 17.97799583333333], ...
	'Tag','XCorRaw', ...
	'ToolBar','none', ...
	'DefaultlineLineWidth',1, ...
	'DefaultaxesLineWidth',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat2, ...
	'FontName','Arial', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[6.75 4.5 66.75 21.75], ...
	'String','Load Data', ...
	'Tag','LoadX');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat3, ...
	'FontName','Arial', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[444.75 4.5 66.75 21.75], ...
	'String','Exit', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat4, ...
	'FontName','Arial', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[371.75 4.5 66.75 21.75], ...
	'String','Export Picture', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat5, ...
	'FontName','Arial', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[152.75 4.5 66.75 21.75], ...
	'String','Save Matrix', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat6, ...
	'FontName','Arial', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[79.75 4.5 66.75 21.75], ...
	'String','Load Matrix', ...
	'Tag','LoadX');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat7, ...
	'FontName','Arial', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[298.75 4.5 66.75 21.75], ...
	'String','Save WK1', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ForegroundColor',[0.4 0.4 0.4], ...
	'ListboxTop',0, ...
	'Position',[9 39 303 133], ...
	'Style','frame', ...
	'Tag','Frame4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[66 110.25 90 12], ...
	'String','Window (ms)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat8, ...
	'ListboxTop',0, ...
	'Position',[24.75 109.5 39.75 13.5], ...
	'String','200', ...
	'Style','edit', ...
	'Tag','Window', ...
	'TooltipString','Only used for the Ian method');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[231 72.75 72.75 13.5], ...
	'String','Correlation Method', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat9, ...
	'ListboxTop',0, ...
	'Position',[170.25 72.75 58.5 17.25], ...
	'String',mat10, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu2', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[66 75 90 12], ...
	'String','To Time (ms)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat11, ...
	'ListboxTop',0, ...
	'Position',[24.75 74.25 39.75 13.5], ...
	'String','-Inf', ...
	'Style','edit', ...
	'Tag','ToTime');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat12, ...
	'ListboxTop',0, ...
	'Position',[24.75 92.25 39.75 13.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','FromTime');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[66 93 90 12], ...
	'String','From Time (ms)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat13, ...
	'FontName','Arial', ...
	'ListboxTop',2, ...
	'Position',[169.5 99 62.25 16.5], ...
	'String',mat14, ...
	'Style','listbox', ...
	'Tag','SecondCell', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[231 101.25 62.25 12.75], ...
	'String','Second Unit', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[231 125.25 62.25 12.75], ...
	'String','First Unit', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat15, ...
	'FontName','Arial', ...
	'Position',[169.5 122.25 62.25 16.5], ...
	'String',mat16, ...
	'Style','listbox', ...
	'Tag','FirstCell', ...
	'Value',2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[66 127.5 90 12], ...
	'String','Bin Width (ms)', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.4 0.4 0.4], ...
	'FontAngle','italic', ...
	'FontName','Arial', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 0], ...
	'ListboxTop',0, ...
	'Position',[9 155 303 17.5], ...
	'String','Cross Correlation Parameters', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat17, ...
	'ListboxTop',0, ...
	'Position',[24.75 126.75 39.75 13.5], ...
	'String','4', ...
	'Style','edit', ...
	'Tag','BinWidth');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ForegroundColor',[0.4 0.4 0.4], ...
	'ListboxTop',0, ...
	'Position',[315 39 200.25 465], ...
	'Style','frame', ...
	'Tag','Frame3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat18, ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[447.75 268.5 39 14.25], ...
	'String','200', ...
	'Style','edit', ...
	'Tag','Ymaxtext', ...
	'UserData','AxesValues');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat19, ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[339 268.5 39 13.5], ...
	'String','-200', ...
	'Style','edit', ...
	'Tag','Ymintext', ...
	'UserData','AxesValues');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[365.25 282.75 108 15.75], ...
	'String','Y-Axis Min and Max Values:', ...
	'Style','text', ...
	'Tag','StaticYText', ...
	'UserData','AxesValues');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','crosscorg(''Axis'')', ...
	'ListboxTop',0, ...
	'Position',[339 335.25 94.5 15.75], ...
	'String','Automatic Axes', ...
	'Style','checkbox', ...
	'Tag','Axeschk', ...
	'TooltipString','Turn automatic axes on or off', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat20, ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[447.75 304.5 39 14.25], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','Xmaxtext', ...
	'UserData','AxesValues');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat21, ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[339 304.5 39 13.5], ...
	'String','-15', ...
	'Style','edit', ...
	'Tag','Xmintext', ...
	'UserData','AxesValues');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[365.25 319.5 108 15.75], ...
	'String','X-Axis Min and Max Values:', ...
	'Style','text', ...
	'Tag','StaticXText', ...
	'UserData','AxesValues');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat22, ...
	'ListboxTop',0, ...
	'Position',[339 373.5 84.75 11.25], ...
	'String',mat23, ...
	'Style','popupmenu', ...
	'Tag','LightMenu', ...
	'TooltipString','Add an additional light to brighten the plot', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[428.25 371.25 65.25 11.25], ...
	'String','Add a Light', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'FontAngle','italic', ...
	'FontName','Arial', ...
	'FontSize',11, ...
	'ForegroundColor',[0.8 0.8 0], ...
	'ListboxTop',0, ...
	'Position',[315.75 241.5 200 15], ...
	'String','Plot Smoothing', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat24, ...
	'ListboxTop',0, ...
	'Position',[337.5 228 84.75 11.25], ...
	'String',mat25, ...
	'Style','popupmenu', ...
	'Tag','SmoothingMenu', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[425.25 227.25 65.25 11.25], ...
	'String','Smoothing Type', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[426 203.25 65.25 11.25], ...
	'String','Resolution:5', ...
	'Style','text', ...
	'Tag','SmoothingText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat26, ...
	'ListboxTop',0, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[336.75 204 87 12.75], ...
	'SliderStep',[0.1 0.2], ...
	'Style','slider', ...
	'Tag','SmoothingSlider', ...
	'Value',5);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[427.5 395.25 65.25 11.25], ...
	'String','Lighting', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat27, ...
	'ListboxTop',0, ...
	'Position',[339 396.75 84.75 11.25], ...
	'String',mat28, ...
	'Style','popupmenu', ...
	'Tag','ShadingMenu', ...
	'TooltipString','Choose lighting for surface plots', ...
	'Value',4);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','makecmap(gcf,''fig'')', ...
	'ListboxTop',0, ...
	'Position',[395.25 174.75 39.75 15], ...
	'String','Colormap', ...
	'Tag','CMapButton', ...
	'TooltipString','Edit the Plot Colours...');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','rotate3d', ...
	'ListboxTop',0, ...
	'Position',[325.5 174 39.75 15], ...
	'String','Rotate3D', ...
	'Tag','RotateButton', ...
	'TooltipString','Rotate the Plot');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','labels', ...
	'ListboxTop',0, ...
	'Position',[465.75 173.25 39.75 15], ...
	'String','Labels', ...
	'Tag','LabelButton', ...
	'TooltipString','Change the X,Y and title labels');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[427.5 466.5 65.25 11.25], ...
	'String','Plot Type', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[427.5 442.5 65.25 11.25], ...
	'String','Color Map', ...
	'Style','text', ...
	'Tag','CmapText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[427.5 418.5 65.25 11.25], ...
	'String','Shading Type', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat29, ...
	'ListboxTop',0, ...
	'Position',[339 420 84.75 11.25], ...
	'String',mat30, ...
	'Style','popupmenu', ...
	'Tag','ShadingMenu', ...
	'TooltipString','Don''t use flat or faceted for surface and checkerboard plots', ...
	'Value',2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat31, ...
	'ListboxTop',0, ...
	'Position',[339 444 84.75 11.25], ...
	'String',mat32, ...
	'Style','popupmenu', ...
	'Tag','CMapMenu', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat33, ...
	'ListboxTop',0, ...
	'Position',[339 468 84.75 11.25], ...
	'String',mat34, ...
	'Style','popupmenu', ...
	'Tag','TypeMenu', ...
	'Value',3);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.4 0.4 0.4], ...
	'FontAngle','italic', ...
	'FontName','Arial', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 0], ...
	'ListboxTop',0, ...
	'Position',[315 486 200 17], ...
	'String','Plot Parameters', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat35, ...
	'ListboxTop',0, ...
	'Position',[335.25 68.25 155.25 14.25], ...
	'String',mat36, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'TooltipString','Choose further analysis methods', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','crosscorg(''PlotMatrix''); ', ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[468 40.875 39.75 15], ...
	'String','Replot', ...
	'Tag','CMapButton', ...
	'TooltipString','Will Redraw (but not rerun) the data');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[412.5 115.5 83.25 10.5], ...
	'String','End Bin Time', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[412.5 132.75 83.25 10.5], ...
	'String','Start Bin Time', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat37, ...
	'ListboxTop',0, ...
	'Position',[326.25 116.25 84.75 11.25], ...
	'String',mat38, ...
	'Style','popupmenu', ...
	'Tag','EndBin', ...
	'Value',126);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat39, ...
	'ListboxTop',0, ...
	'Position',[326.25 135 84.75 11.25], ...
	'String',mat40, ...
	'Style','popupmenu', ...
	'Tag','StartBin', ...
	'Value',126);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.4 0.4 0.4], ...
	'FontAngle','italic', ...
	'FontName','Arial', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 0], ...
	'ListboxTop',0, ...
	'Position',[315 155 200 17], ...
	'String','Binning Parameters', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[11.25 32.25 504.75 5.25], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','crosscorg(''ReRun''); ', ...
	'ListboxTop',0, ...
	'Position',[268.5 40.5 39.75 15], ...
	'String','ReRun', ...
	'Tag','CMapButton', ...
	'TooltipString','Reloads and recomputes the previously selected data');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat41, ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[318.75 40.875 39.75 15], ...
	'String','Values', ...
	'Tag','CMapButton', ...
	'TooltipString','See the Raw Matrix Values');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat42, ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[159 47.25 81 13.5], ...
	'String','See Abstract Art...', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Toys Toys Toys....');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat43, ...
	'ListboxTop',0, ...
	'Position',[338.25 351 67.5 14.25], ...
	'String','Zoom Toggle', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton1', ...
	'TooltipString','This allows you to select areas to enlarge with the mouse');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat44, ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[326.25 93 84.75 11.25], ...
	'String',mat45, ...
	'Style','popupmenu', ...
	'Tag','RatioValue', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontName','Arial', ...
	'ListboxTop',0, ...
	'Position',[412.5 93 83.25 10.5], ...
	'String','Ratio Estimate', ...
	'Style','text', ...
	'Tag','LModelText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat46, ...
	'ListboxTop',0, ...
	'Position',[24.75 57 39.75 13.5], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','StartTrial');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[66 57.75 90 12], ...
	'String','Start Trial', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat47, ...
	'ListboxTop',0, ...
	'Position',[24.75 40.5 39.75 13.5], ...
	'String','-Inf', ...
	'Style','edit', ...
	'Tag','EndTrial', ...
	'TooltipString','Set to -inf to use till last trial');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[66 40.5 90 12], ...
	'String','End Trial', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',8, ...
	'Position',[420 40.5 42.75 14.25], ...
	'String',mat48, ...
	'Style','listbox', ...
	'Tag','PolyBox', ...
	'TooltipString','Use to Set Polynomial Order for HwHH', ...
	'Value',8);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[369.75 40.5 45 14.25], ...
	'String',mat49, ...
	'Style','listbox', ...
	'Tag','IntBox', ...
	'TooltipString','Use For Interpolated Fit', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',mat50, ...
	'FontName','Arial', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[225.75 3.75 66.75 21.75], ...
	'String','Save for Model', ...
	'Tag','Pushbutton1', ...
	'TooltipString','Saves the data in a format readable by the RF-Modeller');
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat51, ...
	'LineWidth',1, ...
	'Position',[48 285 346 355], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4985507246376812 -0.06779661016949157 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.08405797101449275 0.4971751412429379 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.1391304347826087 1.112994350282486 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4985507246376812 1.019774011299435 9.160254037844386], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
if nargout > 0, fig = h0; end
